### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by iamvivekkaushik** [merixstudio/flutter-vizier-challenge#1]
I am unable to run the project, `build.gradle` files are missing from the android folder. It also keeps giving some warning about moving to `AndroidEmbedding` version `2` but the project is already using version 2 in the Android Manifest file.

**Comment by aisivan36** [comment]
You have to set the minSdkVersion to 21 in the android/app/build.gradle

**Comment by aisivan36** [comment]
I have fixed it you can now clone mine
https://github.com/aisivan36/flutter-vizier-challenge

**Comment by mateusztylman** [comment]
Thank you for supporting our challenge, I've fixed the issue already.  
We've added a more extensive .gitignore and missing build.gradle files. 
Check now.
